### ISSUE TITLE
Internal API - no rights statement on images with blank CC status

### ISSUE THREAD

**Issue by f27wood** [NationalMuseumAustralia/Collection-API#105]
When testing the images in narratoives, I noticed that images that have a blank CC status, do not include a rights statement.

This is for the internal API only.

Example:

https://data.nma.gov.au/object/33225?apikey=swIxipP4bWPvL0PTMyP8e7Igtv1ArOfk
https://data.nma.gov.au/object/33225?apikey=swIxipP4bWPvL0PTMyP8e7Igtv1ArOfk&format=json-ld

Compared to a restricted image example:
https://data.nma.gov.au/object/10858?apikey=swIxipP4bWPvL0PTMyP8e7Igtv1ArOfk
https://data.nma.gov.au/object/10858?apikey=swIxipP4bWPvL0PTMyP8e7Igtv1ArOfk&format=json-ld

Suggest adding rights info as follows.

JSON-LD

          "component" : 
          { "id" : "Contact the National Museum of Australia before using this image",
            "type" : "Right",
            "label" : "Copyright yet to be determined" } } } },

Smple DC

 "hasVersion" : 
    [ 
      { "id" : "MA64991957",
        "type" : "StillImage",
        "identifier" : "http:\/\/data.nma.gov.au\/media\/MA64991957#",
        "rights" : "Contact the National Museum of Australia before using this image",
        "rightsTitle" : "Copyright yet to be determined",
        "hasVersion" : 

However, I am not sure as to whether the id and rights should be "Contact the National Museum of Australia before using this image", or a link to All rights reserved, or left blank as it is yet to be determined?

As an example, on Trove, the image rights for these records will be displayed as follows:

Image: Copyright yet to be determined. Contact National Museum of Australia before using this image.
Text: Copyright National Museum of Australia / CC BY-NC https:/​/​creativecommons.org/​licenses/​by-nc/​4.0/​

**Comment by Conal-Tuohy** [comment]
Pre-processs EMu objects XML to insert default statement when missing.

**Comment by f27wood** [comment]
Although thinking this through, the internal API will be used by some external developers such as Trove.. so I am now thinking that we do use it as above.

As internal users of the API can always not use that statement, and they are likely to get copyright clearance for internal use.

**Comment by f27wood** [comment]
As discussed, here is an example record with the status of "Undetermined" which means we have reviewed it and cannot determine the copyright owner.

IRN: 125949

It looks like the rights statement and reason has already been included, so all should be AOK as shown below.

Example from prod:

https://data.nma.gov.au/object/125949?apikey=XXX

SIMPLE
        "rightsTitle" : "All Rights Reserved",
        "rightsReason" : "Status undetermined",

JSON-LD
           "classified_as" : "http:\/\/vocab.getty.edu\/aat\/300404457",
              "value" : "Status undetermined" },
            "component" : 
            { "id" : "http:\/\/rightsstatements.org\/vocab\/InC\/1.0\/",
              "type" : "Right",
              "label" : "All Rights Reserved" } } } },

**Comment by Conal-Tuohy** [comment]
Regarding what to use as the identifier for the "yet to be determined" status, I believe I have found relevant concepts in the "Rights Statements" vocabulary: https://rightsstatements.org/page/1.0/?language=en#collection-other

I would like to use one of these terms because they are standard terms, and I think one of the first two will be correct in every case, but I'm not sure if a blank status necessarily implies one or the other? It seems to me that a blank might potentially imply either. Nevertheless, I've gone ahead with using the first: http://rightsstatements.org/vocab/CNE/1.0/ ("Copyright not evaluated") though I could change it to http://rightsstatements.org/vocab/UND/1.0/ ("Copyright not determined"). 

I think as a practical matter it's not a major difference. Using "Copyright not evaluated" implies that we have not yet got around to it, whereas the second says "we've tried but haven't finished our investigation". It's a question of whether you want to make the claim that you've tried; it seems better to me to not make that claim since we know in some cases it would not be true. Whereas if we use "Copyright not evaluated", we may be stating that we haven't made an attempt to determine rights, when in some cases an attempt actually _may_ have been made. But I think that's a less serious form of misinformation; plus it carries more of an implication that contacting the Museum about obtaining permission might prod someone to investigate the image further (which is a good implication to carry).

So while I was at it I added the possibility of supporting an additional option in the relevant EMu field, so that when curators _have_ attempted to determine rights, and not (yet) succeeded, they can record that fact with a status of "Copyright not determined".

**Comment by f27wood** [comment]
Noting record to test once the ETL has finished:

https://csapi-test.nma.gov.au/object/33225?apikey=4EsxHzPe4aDUDUBK5B38SIWWNrTjnEIj

**Comment by Conal-Tuohy** [comment]
yeah ... I am investigating this now, myself :-(

**Comment by Conal-Tuohy** [comment]
... and incidentally I've realised there's a regression error in that the "public" API doesn't filter out records in which copyright has not been evaluated:

http://nma-dev.conaltuohy.com/object/33225

... but this is a different problem.

**Comment by f27wood** [comment]
Tested with these two records

Copyright not yet evaluated:
https://csapi-test.nma.gov.au/object/33225?apikey=4EsxHzPe4aDUDUBK5B38SIWWNrTjnEIj
This is all AOK as follows

        "type" : "StillImage",
        "identifier" : "http:\/\/csapi-test.nma.gov.au\/media\/MA22876993#",
        "rights" : "http:\/\/rightsstatements.org\/vocab\/CNE\/1.0\/",
        "rightsTitle" : "Copyright not evaluated",
        "rightsReason" : "Copyright has not yet been determined; please contact the National Museum of Australia to request clearance before re-use.",
        "hasVersion" : 

Copyright evaluated and is undetermined:
https://csapi-test.nma.gov.au/object/38677?apikey=4EsxHzPe4aDUDUBK5B38SIWWNrTjnEIj

Please add the words in bold below

        "type" : "StillImage",
        "identifier" : "http:\/\/csapi-test.nma.gov.au\/media\/MA68824613#",
        "rights" : "http:\/\/rightsstatements.org\/vocab\/UND\/1.0\/",
        "rightsTitle" : "Copyright undetermined**; please contact the National Museum of Australia to request clearance before re-use.**",
        "hasVersion" :

**Comment by f27wood** [comment]
Oh hang on - my last comment was incorrect 2. just needs a rightsReason added. I changed this above.

**Comment by f27wood** [comment]
Hmm actually, it is OK as is.. so closing this.
