### ISSUE TITLE
`InwardLoan` handling

### ISSUE THREAD

**Issue by Conal-Tuohy** [NationalMuseumAustralia/Collection-API#134]
Fiona can you check this please?

While writing up the filtering documentation I discovered that the implementation of the `InwardLoan` handling didn't match what I thought it should be. As it stands, this code (see link below) discards the `InwardLoan` flag of records in the public API. Whereas it seems to me the idea was that it should discard a record which has the `InwardLoan` flag set to "yes". Comments?

https://github.com/NationalMuseumAustralia/Collection-API-ETL/commit/dd7d8ea1c25541ad9270b131a5ef545683882b45#diff-c9fc5087f54d88698f841b6fa8f25bef

**Comment by f27wood** [comment]
Hi Conal, 

The Public API should filter out all loan objects, so no loan objects are included in the Public API.

I can't makes sense of the code as not my thing! But testing this, with the test record below, shows that it is being filtered out of the public API. However if you put an internal API key in, you can see it. This is expected behaviour.

https://data.nma.gov.au/object/228418

Cheers, Fiona
