### ISSUE TITLE
Finding objects in a particular gallery: Landmarks

### ISSUE THREAD

**Issue by srowlands** [NationalMuseumAustralia/Collection-API#29]
I am trying to find all objects within a given gallery (e.g http://www.nma.gov.au/exhibitions/landmarks/home). It sounds as though the relationship `used_for` (only present in linked-art) can be used to find this, where label matches 'landmarks'.

It appears as though there is no way to query on values in `used_for` (at least according to the docs) -- is there some other means to search for these objects?

**Comment by staplegun** [comment]
This is now possible: https://csapi-test.nma.gov.au/object?limit=5&location=landmarks

**Comment by f27wood** [comment]
Tested AOK, apart from the Gallery names not being the full name, which is in another issue and for us to correct.

And can the location be a drop-down in the API Explorer?

**Comment by staplegun** [comment]
It's there, but I used the label "Exhibit" as I was thinking "Location" could be confused with place. 

Which brings up the question of what labels are helpful in the drop-downs, e.g. I used "Date" instead of "Temporal"?

The full list is here: https://github.com/Conal-Tuohy/NMA-API/blob/master/apiexplorer.html

**Comment by f27wood** [comment]
Ahhh I see! I agree about date. Not sure about Exhibit. Will check the others too and get back to you if any changes.

**Comment by staplegun** [comment]
Searching by location is operational in production. More granular searching is being worked on in #77 and #79.
