### ISSUE TITLE
Include image links in objects inside narratives

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#32]
In narrative records, for each object, the JSON-LD format includes the object's id, label, Collection Explorer link, and images. This makes it possible to show a list of objects with titles and thumbnails.

The images and Collection Explorer links are missing from the simple DC format, so thumbnails cannot be shown.

**Comment by staplegun** [comment]
Outstanding issues:

- JSON-LD *does* include the object's thumbnail image link, but is still missing from Simple format
- JSON-LD *does* include the object's Collection Explorer link, but is still missing from Simple format

Example: Narrative 2358, Object 147507 has images

**Comment by staplegun** [comment]
Link to Collection Explorer now appears in Simple format, but object's thumbnail image link is removed from both JSON-LD and Simple format.

**Comment by Conal-Tuohy** [comment]
Leave for version 1.1 as a test of the versioning system.

**Comment by f27wood** [comment]
Can we move this up as a priority for v1.0 as we need it for the new website, as one of the functionalities is to embed a narrative in the website. By embedding - it shows the objects in that narrative, their title and preview image.

And if possible including the thumbnail and preview image, as often the thumbnail image is too small so it would be good to include the preview image as well.

**Comment by Conal-Tuohy** [comment]
This is because of two bugs in the RDF redaction step (i.e. the step in which the RDF graph about a single resource is trimmed). This step actually now does makes quite a number of different redactions, particularly around images, and the logic of those redactions is tangled up. Images are redacted if:

- they are unlicenced
- they are EMu images of an object which has Piction images
- they are images (other than preview and thumbnail) of an object within an aggregation

This tangled logic has already led to a few bugs, but there are still at least 2 errors in the logic which are causing this issue #32, so I've decided to split the redaction step into a series of independent steps each with a single task, so that the logic is clearer, and I expect that will fix the bugs or at least allow them to be fixed easily and the code maintained more easily in future.

**Comment by Conal-Tuohy** [comment]
Narratives now contain images: e.g. http://csapi-test.nma.gov.au/narrative/3371#
