### ISSUE TITLE
Signup form for new API key

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#36]
Provide an online form to signup for a new API key. Provide name and email (to receive the API key and service notifications).

**Comment by f27wood** [comment]
See #61 for the form content.

**Comment by Conal-Tuohy** [comment]
Need separate password-protected form for internal API key.

**Comment by f27wood** [comment]
The form seems to be working AOK for public and internal apart form the fact that if I apply for a key with the same email address, for the same API, I get a new key rather than the existing key. (not a show stopper).

Still to do - added as tasks for v1.0:

Thank you message for the publci API to be embedded within the nma website, or can this be a re-direct? i.e. the form is processed then the person is redirected to a URL I give you, so I can then create the thank you page in our website.

Thank you email to be reviewed and updated.

**Comment by f27wood** [comment]
I will move this to v1.0 as the tasks required to be completed for v0.1 have been.

**Comment by Conal-Tuohy** [comment]
Yes let's do a redirect; if you can give me the URL I will make the form redirect to it after submission.

**Comment by Conal-Tuohy** [comment]
```<c:header name="location" value="http://www.nma.gov.au/collections/api/thankyou"/>```

**Comment by f27wood** [comment]
Completed, with one out-standing issues documented elsewhere, so closing this one.
https://github.com/NationalMuseumAustralia/Collection-API/issues/87
