### ISSUE TITLE
Add secondary type field

### ISSUE THREAD

**Issue by staplegun** [NationalMuseumAustralia/Collection-API#45]
Adds more typing information, from EMu `TitSecondaryObjectType` field.

**Comment by staplegun** [comment]
Searchable as a separate field `additionalType` : https://csapi-test.nma.gov.au/object?additionalType=prints

**Comment by f27wood** [comment]
This is OK as is, but noting (if you can confirm) that the AdditionalType is using the EMU field TitObjectName rather than TitSecondaryObjectType?

And at some stage, we would also like to include an additional additional type, as some objects have the TitSecondaryObjectType populated. I will add that as a separate issue/task.

**Comment by staplegun** [comment]
Both `TitObjectName` and `TitSecondaryObjectType` are going into the same field: `crm:P2_has_type` in JSON-LD, which goes into `additionalType` in simple format.

For example: https://csapi-test.nma.gov.au/apiexplorer.html?id=object/230903

- TitObjectName = Medals
- TitSecondaryObjectType = Trophies

**Comment by f27wood** [comment]
OK great, already done! I can see this in the DC format. However, I cannot find where the additional types are referenced in the linked art version... what am I looking for?

**Comment by Conal-Tuohy** [comment]
https://csapi-test.nma.gov.au/object/230903?format=json-ld

See 'classified_as'
